### ISSUE TITLE
SPSS java library

### ISSUE THREAD

**Issue by lockTP** [infsci2711/MultiDBs-FilesAPIs2DBs-WebClient#3]
Does anybody know anything about SPSS java lib? Please help me out here. Or anybody can do this job?

**Comment by wed26** [comment]
what do you want to predict for? Or how do you want to do with SPSS?

**Comment by EvgenyKarataev** [comment]
@wed26 I don't understand "what do you want to predict for?" Did you want to ask me? We just need to be able to extract data from SPSS file, that's it.

**Comment by lockTP** [comment]
Basically, we need to develop a java program, the input is SPSS file, and the output should be some kind of java structure data which can be stored in the database.

**Comment by EvgenyKarataev** [comment]
@wed26 yes, once you read the data form SPSS file into a java structure, then we can do some stuff with it like store to DB or pass it to other projects.

**Comment by lockTP** [comment]
This issue should be put in the Server project. If you got any question about SPSS, please move to Server project and post issues over there.

**Comment by EvgenyKarataev** [comment]
@lockTP  then you should probably close this issue.
